#!/bin/bash
current=$(bspc query -D -d)
name="floating_"$current"_terminal"

size=$(xdpyinfo | grep dimension | awk '{print $2}')
width=$(echo $size | awk -F 'x' '{print $1}')
height=$(echo $size | awk -F 'x' '{print $2}')
term_width=$(($width / 2))
term_height=$(($height / 3))
xoffset=$((($width - $term_width) / 2))
yoffset=$(($height - ($term_height + ($(bspc config window_gap) * 3))))

if [[ -z $(xdotool search --classname $name) ]]; then
	xterm -name $name -ls -fa "Hack:size=9" &
	sleep 0.08
	xdotool search --classname $name windowsize $term_width $term_height windowmove $xoffset $yoffset
else
	if [[ -z $(xdotool search --classname $name"_hidden") ]]; then
		xdotool search --classname $name windowunmap set_window --classname $name"_hidden" windowsize $term_width $term_height windowmove $xoffset $yoffset windowfocus
	else
		xdotool search --classname $name"_hidden" windowmap set_window --classname $name
	fi
fi
