#! /bin/sh

sxhkd -m -1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width		2
bspc config window_gap			12
bspc config top_padding			14
bspc config presel_feedback_color	"#5b5056"

bspc config split_ratio			0.5
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_by_distance		true
bspc config history_aware_focus		true
bspc config focus_follows_pointer	true

bspc config external_rules_command $HOME/.config/bspwm/external_rules

bspc rule -a Matplotlib state=floating

feh --bg-scale $HOME/.config/bspwm/sun.jpg

cd $HOME/.config/bspwm/panel
./panel &
