#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#zmodload zsh/zprof

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
	source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias vim="nvim"

export WORKON_HOME=$HOME/.venvs
export PROJECT_HOME=$HOME/git
export PATH=$PATH:~/.bin

if [[ -s "/etc/bash_completion.d/virtualenvwrapper" ]]; then
	source /etc/bash_completion.d/virtualenvwrapper
fi

if [[ -s "~/.venvs/default/bin/activate" ]]; then
	source ~/.venvs/default/bin/activate
fi

#zprof
